config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root :to => 'root#index'
  get :news, to: 'news#index'

  get :public, to: 'public_root#index', as: 'public_root'

  get :setup, to: 'setup#index'
  post :setup, to: 'setup#create'
  put :setup, to: 'setup#update'

  get :terms, to: 'terms_of_use#index'
  post :terms, to: 'terms_of_use#accept'

  get "vertical_navs/:navable_type/:navable_id", to: 'vertical_navs#show', as: :vertical_nav
  resources :nav_nodes

  # Users should be allowed to change their password(update registration), but not to sign up(create registration)
  devise_for :user_accounts, controllers: {sessions: "sessions", masquerades: 'user_account_masquerades'}, :skip => [:registrations]
  devise_scope :user_account do
    get 'sign_in' => 'sessions#new', as: :sign_in
    post 'sign_in' => 'sessions#create'
    delete 'sign_out' => 'sessions#destroy', as: :sign_out
    get 'change_password' => 'devise/registrations#edit', :as => 'edit_registration'
    get 'change_password' => 'devise/registrations#edit', :as => 'edit_password'
    get 'change_password' => 'devise/registrations#edit', :as => 'change_password'
    get 'reset_password' => 'devise/passwords#edit', as: 'reset_password' # from email with token
    put 'change_password/:id' => 'devise/registrations#update', :as => 'registration' #todo: change to patch in rails 4.0
    get 'forgot-password', to: 'devise/passwords#new'
    get 'passwort-vergessen', to: 'devise/passwords#new'

    get "/auth/:provider/callback", to: 'sessions#create'
  end

  get 'search/guess', to: "search#lucky_guess"
  get 'search/preview', to: "search#preview"
  get :search, to: "search#index"
  get 'opensearch.xml', to: 'search#opensearch', as: 'opensearch'

  get "compact-nav-search(.:format)/(:query)", to: "compact_nav_search#show", as: 'compact_nav_search'

  mount Judge::Engine => '/judge'

  resources :users do
    put :forgot_password, on: :member
    resource :account, controller: 'user_accounts'
    get :events, to: 'events#index'
    get :profile, to: 'profiles#show'
    get :profile_fields, to: 'profile_fields#index'
    get :settings, to: 'user_settings#show'
    put :settings, to: 'user_settings#update'
    get :memberships, to: 'memberships#index'
    get :badges, to: 'user_badges#index'
    get :activities, to: 'activities#index'
    get :contact, to: 'user_contact_information#index', as: 'contact_information'
    get :blog_posts, to: 'user_posts#index'
    get :sign_in, to: 'user_masquerade#show', as: 'masquerade'
    post :renew_cache, to: 'cache_renewals#create'
    get :renew_cache, to: 'cache_renewals#create'
    get :groups, to: 'groups#index'
    get :documents, to: 'documents#index'
  end

  get :settings, to: 'user_settings#index'
  get 'settings/app', to: 'app_settings#index', as: 'app_settings'
  resources :settings, as: 'rails_settings_scoped_setting'
  resources :settings, as: 'setting'

  get :authorized_users, to: 'authorized_users#index'

  get 'groups/:id/address_labels/(:filter)/:pdf_type.:format', to: 'groups#show', as: 'group_address_labels'
  #get 'groups/:parent_group_id/subgroups(.:format)', to: 'groups#index', as: 'subgroups'
  get 'groups/:group_id/semester_calendar', to: 'semester_calendars#show', as: '/current_semester_calendar'
  resources :groups do
    get :news, to: 'group_news#index'
    get :subgroups, to: 'groups#index'
    get 'events/public', to: 'events#index', published_on_local_website: true
    get :events, to: 'events#index'
    resources :semester_calendars
    get :semester_calendar, to: 'semester_calendars#show', as: 'search_semester_calendar'
    resources :posts
    get :pages, to: 'group_pages#index'
    get :profile, to: 'profiles#show'
    get :profile_fields, to: 'profile_fields#index'
    resources :members, controller: 'group_members'
    post 'members/memberships', to: 'memberships/from_members_index#create'
    get :member_data_summaries, to: 'group_member_data_summaries#index'
    get :officers, to: 'officers#index'
    namespace :officers do
      get :history, to: '/officer_history#index'
    end
    get :settings, to: 'group_settings#index'
    get :mailing_lists, to: 'group_mailing_lists#index'
    get :memberships, to: 'memberships#index'
    get :workflows, to: 'workflows#index'
    post :test_welcome_message, to: 'groups#test_welcome_message'
    get :term_report, to: 'term_reports#show'
    resources :room_occupants
    resources :room_occupancies
    get 'terms/:year/:term_type/report', to: 'term_reports#show'
    get 'terms/:year/:term_type/calendar', to: 'semester_calendars#show', as: 'semester_calendar_by_term_and_year'
    get 'exports/:list.:format', to: 'list_exports#show', as: 'list_export'
    post :renew_cache, to: 'cache_renewals#create'
    get :renew_cache, to: 'cache_renewals#create'
    namespace :excel_imports do
      resources :users
    end
    get :website, to: 'websites#show'
    post :website, to: 'websites#create'
    get :documents, to: 'documents#index'
  end

  resources :websites

  namespace :groups, path: "" do
    resources :groups_of_groups do
      get 'exports/table.:format', to: 'groups_of_groups/table_exports#show', as: 'table_export'
    end
    resources :corporations_parents, controller: 'groups_of_groups'
    resources :rooms
    resources :free_groups
  end

  resources :free_groups, controller: 'groups/free_groups'

  get :corporations, to: 'corporations#index'
  resources :corporations, controller: 'groups' do
    get :accommodations, to: 'accommodations#index'
    resources :accommodation_sepa_debits
  end
  resources :officer_groups

  namespace :officers do
    get ':flag', to: 'by_flag#index'
  end

  resources :members, only: [:index], controller: :members_dashboard

  resources :pages do
    get :photo_contest, to: 'photo_contests#show'
    get :activities, to: 'activities#index'
    get :settings, to: 'page_settings#index'
    get :attachments, to: 'attachments#index'
    get :permalinks, to: 'permalinks#index'
    get :settings, to: 'page_settings#index'
    resources :publications, only: [:create], controller: :page_publications
    post :renew_cache, to: 'cache_renewals#create'
    get :renew_cache, to: 'cache_renewals#create'
    resources :logos, controller: :logos
    resources :relocations, controller: 'page_relocations'
    get :documents, to: 'documents#index'
  end

  namespace :pages, path: '' do
    resources :public_pages, path: '/public'
    resources :public_events_pages, path: '/public/events'
    resources :public_gallery_pages, path: '/public/galleries'
  end

  get :home_pages, to: 'pages/home_pages#index'
  post :home_pages, to: 'pages/home_pages#create'

  resources :calendars

  resources :logos

  resources :mailing_lists
  get :lists, to: 'mailing_lists#index'

  namespace :structureables do
    delete 'sub_entries/destroy', to: 'sub_entries#destroy'
    namespace :sub_entries do
      resources :existing_groups
      resources :pages
      resources :groups
    end
  end

  resources :projects

  namespace :activities do
    get :exports, to: 'exports#index'
    #get :addresses, to: 'addresses#index'
    get :charts, to: redirect('/charts/activities')
  end
  resources :activities
  resources :requests

  namespace :charts do
    get :activities, to: 'activities#index'
    get 'activities/per_corporation_and_time', to: 'activities#per_corporation_and_time'
    get :term_reports, to: 'term_reports#index'
    get 'term_reports/members/per_corporation_and_term', to: 'term_reports/members#per_corporation_and_term'
  end

  resources :term_reports do
    post :submit, to: 'term_report_submissions#create'
    post :accept, to: 'term_report_acceptions#create'
    post :recalculate, to: 'term_report_recalculations#create'
    get :export, to: 'term_reports/exports#show', on: :collection
  end

  get :term_report, to: 'term_reports#show', as: :search_term_report

  get :scores, to: 'corporation_scores#index', as: :corporation_scores

  post :create_officers_group, to: 'officers#create_officers_group'

  resources :blogs do
    delete :subscriptions, to: 'blog_subscriptions#destroy'
    resources :subscriptions, controller: 'blog_subscriptions'
  end
  get 'confirm_blog_subscription/:token', to: 'blog_subscription_confirmations#create', as: :create_blog_subscription_confirmation
  resources :blog_posts
  resources :attachments do
    get 'description(.:format)', to: 'attachment_descriptions#show'
  end

  resources :documents
  resources :profile_fields
  resources :memberships
  resources :status_memberships
  resources :relationships
  resources :small_ads, path: 'gesuche-und-angebote'

  get 'events/public', to: 'events#index', published_on_global_website: true, all: true, as: 'public_events'
  resources :events do
    post :join, to: 'events#join'
    get :join, to: 'events#join_via_get', as: 'join_via_get'
    delete :leave, to: 'events#leave'
    post 'invite/:recipient', to: 'events#invite', as: 'invite'
    get :attachments, to: 'attachments#index'
    post :renew_cache, to: 'cache_renewals#create'
    get :renew_cache, to: 'cache_renewals#create'
  end
  resources :semester_calendars do
    member do
      patch :update_term_and_year, to: 'semester_calendars#update_term_and_year'
    end
  end

  get 'posts/preview', to: 'posts#preview', as: 'post_preview'
  resources :posts do
    get :deliveries, to: 'post_deliveries#index'
    put :deliver, to: 'posts#deliver'
    get :attachments, to: 'attachments#index'
  end
  resources :comments

  patch 'notifications/read_all', to: 'notifications#read_all', as: 'read_all_notifications'
  resources :notifications

  resources :issues

  post :support_requests, to: 'support_requests#create'

  get 'avatars', to: 'avatars#show'
  get 'emojis', to: 'emojis#index'

  resources :badges, controller: 'user_badges'

  get :statistics, to: 'statistics#index', as: 'statistics_index'
  get "/statistics/:list", to: 'statistics#show', as: 'statistics'

  resources :bookmarks

app/models/concerns/group_mailing_lists.rb
concern :GroupMailingLists do

  # Returns all mailing list profile fields, i.e. email addresses that
  # are used as mailing list for that group.
  #
  def mailing_lists
    self.profile_fields.where(type: 'ProfileFields::MailingListEmail')
  end

  # All mailing lists, including the ones of the sub groups.
  #
  def groups_with_mailing_lists
    ([self] + descendant_groups.order(:id)).select { |g| g.mailing_lists.any? }
  end

  def chargen_mailing_list
    chargen.mailing_lists.first if chargen
  end

  # Possible settings for the sender filter, i.e. the group attribute that determines
  # whether an incoming post is accepted or rejected.
  #
  def mailing_list_sender_filter_settings
    %w(open users_with_account corporation_members group_members officers group_officers global_officers)
  end

  # Checks whether the given user is allowed to send an email to the mailing lists
  # of this group.
  #
  def user_matches_mailing_list_sender_filter?(user)
    case self.mailing_list_sender_filter.to_s
    when 'open'
      true
    when 'users_with_account'
      user && user.has_account?
    when 'corporation_members'
      user && user.member_of?(self.corporation)
    when 'group_members'
      user && user.member_of?(self)
    when 'officers'
      user && user.officer_of_anything?
    when 'group_officers'
      user && user.in?(self.officers)
    when 'global_officers'
      user && user.global_officer?
    when '', nil  # (default setting)
      if self.kind_of? OfficerGroup
        # Everyone can contact officers.
        true
      elsif self.corporation.present?
        # If the group has an associated corporation, all members
        # of the corporation can post.
        user && user.member_of?(self.corporation)
      else
        # If this is a regular group, all group members can post.
        user && user.member_of?(self)
      end
    else
      false
    end
  end

end

app/controllers/group_mailing_lists_controller.rb
class GroupMailingListsController < ApplicationController
  skip_authorize_resource :only => :index

  def index
    @group = Group.find params[:group_id]
    authorize! :manage_mailing_lists_for, @group

    @email_address_fields = @group.profile_fields.where(type: 'ProfileFields::MailingListEmail')

    set_current_navable @group
    set_current_title "#{t(:manage_mailing_lists)}: #{@group.name}"
  end

end

app/views/group_mailing_lists/index.html.haml
= render partial: 'groups/tabs', locals: {active: 'settings'}

%h1= @title
%div
  %h2= t :what_are_mailing_lists
  %p= markup t :mailing_lists_forward_emails_to_all_group_members
  %p= t :no_need_to_manage_list_members_separately
  
%h1.mailing_lists= t :mailing_list_adresses
%div.section.mailing_list_adresses

  %ul.attributes.profile_fields
    - @email_address_fields.each do |profile_field|
      = profile_field_li(profile_field)

  = add_button(profile_fields_path(:profileable_id => @group.id,
                                   :profileable_type => 'Group',
                                   :profile_field => {:type => 'ProfileFields::MailingListEmail', :label => t(:mailing_list)},
                                   :section => 'mailing_list_adresses'), :method => 'post')

%h1.sender_filter= t :mailing_list_sender_filter
%div.section.sender_filter
  %p
    %strong Absender-Filter:
    = best_in_place @group, :mailing_list_sender_filter, as: :select, collection: Hash[@group.mailing_list_sender_filter_settings.collect { |setting| [setting, I18n.t("sender_filter.#{setting}")] }]
  %p Es werden nur Nachrichten von diesen Absendern zugelassen. Alle übrigen Nachrichten werden abgewiesen.
  

%h1 E-Mail-Verteiler einrichten
%div
  %p 
    %strong Das Einrichten eines neuen E-Mail-Verteilers ist ganz einfach und dauert nur ein paar Minuten, erfordert aber ein paar konzentriert durchgeführte Schritte:
  
  %p
    %ol
      %li
        %p
          %strong Verteiler-Adressen überlegen:
          Eine Verteiler-Adresse muss so gewählt sein, dass auf den ersten Blick klar ist, wen man damit erreicht. Es ist auch möglich, der gleichen Gruppe mehrere Verteiler-Adressen zuzuweisen. Einige Beispiele:
        %p
          %ul
            %li= markup "**Gut**: chargen.berlin@wingolf.org, berliner-chargen@wingolf.org, chargen@berliner-wingolf.de"
            %li= markup "**Gut**: burschen.berlin@wingolf.org, berliner-burschen@wingolf.org, burschen@berliner-wingolf.de"
            %li= markup "**Gut**: aktivitas.berlin@wingolf.org, berliner-aktivitas@wingolf.org, aktivitas@berliner-wingolf.de"
            %li= markup "**Schlecht**: berlin@wingolf.org, berlin@berliner-wingolf.de (Schlecht, da man als Absender nicht erkennen kann, wen man mit dieser Adresse erreicht.)"
      %li
        %p
          %strong Verteiler-Adressen eintragen:
          Trage die gewünschten Verteiler-Adressen in den obigen Abschnitt "Verteiler-Adressen" ein.
        %p
          Sollte eine Adresse vom System nicht akzeptiert werden (in diesem Fall verschwindet sie direkt nach Eingabe einfach wieder), ist sie möglicherweise schon vergeben.
          Wende Dich im Zweifel bitte an unsere Hilfe-Zentrale über den blauen Hilfe-Knopf ganz oben, um Hilfe bei der Lösung dieses Problems zu erhalten.
      %li
        %p
          %strong E-Mail zur Verarbeitung an die Plattform weiterleiten:
          Damit die Plattform eingehende Nachrichten korrekt verarbeiten kann, müssen die Nachrichten in das System eingespeist werden.
        %p 
          %strong (a) wingolf.org: 
          Für wingolf.org-Adressen geschieht das automatisch. Für wingolf.org-Adressen ist also kein weiterer Schritt notwendig.
        %p
          Beachte aber, dass früher bereits händisch eingerichtete wingolf.org-Adressen Bestandsschutz genießen und somit bei der Zustellung von E-Mails vorrangig behandelt werden. Ob eine solche händisch eingerichtete Adresse auf dem Wingolf-E-Mail-Server existiert, kannst Du ebenfalls über unsere Hilfe-Zentrale abfragen.
        %p 
          %strong (b) Andere Adressen (z.B. berliner-wingolf.de):
          Wenn zusätzlich zur wingolf.org-Verteiler-Adresse (z.B. aktivitas.berlin@wingolf.org) eine Adresse einer eigenen Domain gewünscht ist (z.B. aktivitas@berliner-wingolf.de), muss die Zusatz-Adresse (aktivitas@berliner-wingolf.de) an die wingolf.org-Verteiler-Adresse (aktivitas.berlin@wingolf.org) weitergeleitet werden.
        %p
          Dies kann nur durch den Domain-Administrator erfolgen, der für die lokale Domain (berliner-wingolf.de) zuständig ist.
          Wer Administrator der lokalen Domain ist, kann beispielsweise in zwei Klicks über die Who-Is-Abfrage der DENIC-Behörde abgefragt werden:
          %a{href: "http://www.denic.de/domains/whois-service.html"} http://www.denic.de/domains/whois-service.html
        %p
          Und was ist mit "info@berliner-wingolf.de"?
          Kein Problem: Einfach diese Adresse oben eintragen, aber keine Weiterleitung erstellen. Dann wird die Adresse ganz normal in der Kontakt-Liste der Verbindung aufgeführt, aber nicht in das Plattform-Mail-Verteiler-System eingespeist.
          
      %li
        %p
          %strong Adresse testen:
          Der E-Mail-Verteiler ist sofort einsatzbereit.
          Sende eine Test-E-Mail über Dein E-Mail-Programm an die neu eingerichtete Adresse, um zu überprüfen, ob sie korrekt verarbeitet wird.
        %p
          = markup "Wenn Du **Hilfe** benötigst, wende Dich bitte an unsere Hilfe-Zentrale über den **blauen Hilfe-Knopf** oben auf der Plattform oder per E-Mail an support@wingolf.org."
        