config/routes.rb
    get :photo_contest, to: 'photo_contests#show'
    get :activities, to: 'activities#index'
    get :settings, to: 'page_settings#index'
    get :attachments, to: 'attachments#index'
    get :permalinks, to: 'permalinks#index'
    get :settings, to: 'page_settings#index'
    resources :publications, only: [:create], controller: :page_publications
    post :renew_cache, to: 'cache_renewals#create'
    get :renew_cache, to: 'cache_renewals#create'
    resources :logos, controller: :logos
    resources :relocations, controller: 'page_relocations'
    get :documents, to: 'documents#index'
  end

  namespace :pages, path: '' do
    resources :public_pages, path: '/public'
    resources :public_events_pages, path: '/public/events'
    resources :public_gallery_pages, path: '/public/galleries'
  end

  get :home_pages, to: 'pages/home_pages#index'
  post :home_pages, to: 'pages/home_pages#create'

  resources :calendars

  resources :logos

  resources :mailing_lists
  get :lists, to: 'mailing_lists#index'

  namespace :structureables do
    delete 'sub_entries/destroy', to: 'sub_entries#destroy'
    namespace :sub_entries do
      resources :existing_groups
      resources :pages
      resources :groups
    end
  end

  resources :projects

  namespace :activities do
    get :exports, to: 'exports#index'
    #get :addresses, to: 'addresses#index'
    get :charts, to: redirect('/charts/activities')
  end
  resources :activities
  resources :requests

  namespace :charts do
    get :activities, to: 'activities#index'
    get 'activities/per_corporation_and_time', to: 'activities#per_corporation_and_time'
    get :term_reports, to: 'term_reports#index'
    get 'term_reports/members/per_corporation_and_term', to: 'term_reports/members#per_corporation_and_term'
  end

  resources :term_reports do
    post :submit, to: 'term_report_submissions#create'
    post :accept, to: 'term_report_acceptions#create'
    post :recalculate, to: 'term_report_recalculations#create'
    get :export, to: 'term_reports/exports#show', on: :collection
  end

  get :term_report, to: 'term_reports#show', as: :search_term_report

  get :scores, to: 'corporation_scores#index', as: :corporation_scores

  post :create_officers_group, to: 'officers#create_officers_group'

  resources :blogs do
    delete :subscriptions, to: 'blog_subscriptions#destroy'
    resources :subscriptions, controller: 'blog_subscriptions'
  end
  get 'confirm_blog_subscription/:token', to: 'blog_subscription_confirmations#create', as: :create_blog_subscription_confirmation
  resources :blog_posts
  resources :attachments do
    get 'description(.:format)', to: 'attachment_descriptions#show'
  end

  resources :documents
  resources :profile_fields
  resources :memberships
  resources :status_memberships
  resources :relationships
  resources :small_ads, path: 'gesuche-und-angebote'

  get 'events/public', to: 'events#index', published_on_global_website: true, all: true, as: 'public_events'
  resources :events do
    post :join, to: 'events#join'
    get :join, to: 'events#join_via_get', as: 'join_via_get'
    delete :leave, to: 'events#leave'
    post 'invite/:recipient', to: 'events#invite', as: 'invite'
    get :attachments, to: 'attachments#index'
    post :renew_cache, to: 'cache_renewals#create'
    get :renew_cache, to: 'cache_renewals#create'
  end
  resources :semester_calendars do
    member do
      patch :update_term_and_year, to: 'semester_calendars#update_term_and_year'
    end
  end

  get 'posts/preview', to: 'posts#preview', as: 'post_preview'
  resources :posts do
    get :deliveries, to: 'post_deliveries#index'
    put :deliver, to: 'posts#deliver'
    get :attachments, to: 'attachments#index'
  end
  resources :comments

  patch 'notifications/read_all', to: 'notifications#read_all', as: 'read_all_notifications'
  resources :notifications

  resources :issues

  post :support_requests, to: 'support_requests#create'

  get 'avatars', to: 'avatars#show'
  get 'emojis', to: 'emojis#index'

  resources :badges, controller: 'user_badges'

  get :statistics, to: 'statistics#index', as: 'statistics_index'
  get "/statistics/:list", to: 'statistics#show', as: 'statistics'

  resources :bookmarks
  get :my_bookmarks, controller: "bookmarks", action: "index"

  resources :workflows do
    put 'execute', on: :member
  end
  put 'workflow_kit/workflows/:id/execute', to: 'workflows#execute'
  put 'users/:user_id/status_workflows/:id/execute(.:format)', to: 'workflows/status_workflows#execute', as: 'execute_status_workflow'

  namespace :decision_making do
    resources :federal_ballots
    resources :ballots do
      resources :signatures
      resources :submissions
    end
  end

  resources :features

  resources :integrations, only: [:index]
  get 'integrations/trello', to: 'integrations/trello#show'

  get :renew_cache, to: 'cache_renewals#create'

  # Dashboards for global admins:
  global_admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.user.global_admin?
  end
  developer_constraint = lambda do |request|
    request.env['warden'].authenticate? && (request.env['warden'].user.user.developer? || request.env['warden'].user.user.global_admin?)
  end
  constraints global_admin_constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Refile File Attachments
  mount Refile.app, at: '/refile', as: :refile_app

  get 'tags/:tag_name', to: 'tags#show', as: :tag
  resources :tags
  resources :tags, path: :acts_as_taggable_on_tags, as: :acts_as_taggable_on_tags

  resources :contact_messages, only: [:new, :create]

  # Email previews
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  post :incoming_mails, to: 'incoming_mails#create', defaults: {format: :json}
  post :incoming_emails, to: 'incoming_mails#create', defaults: {format: :json}
  post :mailgate, to: 'incoming_mails#create', defaults: {format: :json}
  resources :incoming_mails

  get :feeds, to: 'feeds#index', as: :feeds

  # ATTENTION: Changing feed urls might break subscribed feeds!
  get 'feeds/:id(.:format)', to: 'feeds#show', as: :feed

  resources :subscriptions

  resources :beta_invitations
  resources :betas do
    get :invitations, to: 'beta_invitations#index'
  end

  get :vorort, to: 'vororte#show'

  apipie
  get :api, to: 'apipie/apipies#index'
  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'UserAccount', at: 'auth', controllers: {
        sessions: 'api/v1/sessions'
      }
      get :sso, to: 'single_sign_on#sign_in'
      namespace :public do
        resources :groups do
          resources :events
        end
        resources :events
        resources :blog_posts
      end
      resources :events
      resources :users do
        get :corporate_vita, to: 'users/corporate_vita#show'
        get :change_status_button, to: 'users/change_status_button#show'
        get :titles, on: :collection, to: 'users/titles#index'
        get :avatar, to: '/avatars#show'
        post :location, on: :collection, to: 'users/locations#create'
        put :location, on: :collection, to: 'users/locations#update'
        post :change_status, to: 'change_status#create'
      end
      resources :groups do
        resources :members
      end
      resources :corporations do
        resources :rooms
      end
      resources :offices
      resources :room_occupancies
      resources :documents
      resources :pages
      resources :songs
      resources :posts do
        resources :attachments
        post :publish, to: 'posts/publications#create'
        put :public_website_publications, to: 'posts/public_website_publications#update'
      end
      resources :attachments
      resources :comments
      get :current_user, to: 'current_user#show'
      get :current_role, to: 'current_role#show'
      resources :memberships
      namespace :navables do
        put :vertical_nav_configuration, to: 'vertical_nav_configuration#update'
      end
      get :search_contacts, to: 'search_contacts#index'
      get :search_users, to: 'search_users#index'
      get :search_groups, to: 'search_groups#index'
      get :search_pages, to: 'search_pages#index'
      get :navigation, to: 'navigation#show'
      get 'search/preview', to: '/search#preview', defaults: {format: :json}
    end
  end


  get "/attachments/:id(/:version)/*basename.:extension", controller: 'attachment_downloads', action: 'show', as: 'attachment_download'

  # We need 'show' for short permalinks and 'put' to make best_in_place work,
  # which does not distinguish when generating the url.
  # https://github.com/bernat/best_in_place/blob/master/lib/best_in_place/helper.rb
  #
  {get: 'show', put: 'update'}.each do |http_method, controller_method|
    send http_method, '*permalink', to: "tags##{controller_method}", constraints: lambda { |request| Permalink.for_host(request.host).where(reference_type: 'ActsAsTaggableOn::Tag', url_path: request[:permalink]).any? }
    send http_method, '*permalink', to: "blogs##{controller_method}", constraints: lambda { |request| Permalink.for_host(request.host).where(reference_type: 'Page', url_path: request[:permalink]).first.try(:reference).kind_of?(Blog) }
    send http_method, '*permalink', to: "blog_posts##{controller_method}", constraints: lambda { |request| Permalink.for_host(request.host).where(reference_type: 'Page', url_path: request[:permalink]).first.try(:reference).kind_of?(BlogPost) }
    send http_method, '*permalink', to: "pages##{controller_method}", constraints: lambda { |request| Permalink.for_host(request.host).where(reference_type: 'Page', url_path: request[:permalink]).any? }
    send http_method, '*permalink', to: "groups##{controller_method}", constraints: lambda { |request| Permalink.for_host(request.host).where(reference_type: 'Group', url_path: request[:permalink]).any? }
  end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  load_and_authorize_resource except: [:read_all, :index]
  skip_authorization_check only: [:read_all]
  
  def index
    @notifications = current_user.notifications.order('created_at desc')
    authorize! :index, Notification
    
    set_current_navable Page.intranet_root
    set_current_title t(:notifications)
    set_current_activity :looks_at_notifications
  end
  
  def show
    @notification.update_attribute :read_at, Time.zone.now
    redirect_to @notification.reference_url
  end
  
  # PATCH notifications/read_all
  #
  # This marks all notifications of the current_user as read.
  #
  def read_all
    current_user.notifications.unread.update_all read_at: Time.zone.now
    redirect_to :back, change: 'notifications_menu'
  end
  
end

app/views/notifications/_comment_notification.html.haml
- # We need the inline styling for emails.

.notification
  %div{style: 'float: left; margin-right: 10px'}
    = user_avatar(notification.author)
  %div{style: 'overflow: hidden'}
    %small
      = link_to notification.author.title, notification.author if notification.author
      = localize(notification.created_at)
    .notification_body
      %p
        %strong= link_to notification.message, notification
      %p= markup notification.text

    .notification_links
      %small
        = link_to t(:write_a_comment), notification

app/views/notifications/_generic_notification.html.haml
- # We need the inline styling for emails.

.notification
  %div{style: 'float: left; margin-right: 10px'}
    = user_avatar(notification.author) if notification.author
  %div{style: 'overflow: hidden'}
    %small
      = link_to notification.author.title, notification.author if notification.author
      = localize(notification.created_at)
    .notification_body
      %p
        %strong= link_to notification.message, notification
      %p= markup notification.text

app/views/notifications/_notification.html.haml
- notification || raise(ActionController::ParameterMissing, 'no notification given')

- case notification.reference_type
- when 'Post'
  = render partial: 'notifications/post_notification', locals: {notification: notification}
- when 'Comment'
  = render partial: 'notifications/comment_notification', locals: {notification: notification}
- when 'User'
  = render partial: 'notifications/user_status_notification', locals: {notification: notification}
- when 'Group'
  = render partial: 'notifications/welcome_notification', locals: {notification: notification}
- else
  = render partial: 'notifications/generic_notification', locals: {notification: notification}

app/views/notifications/_notifications_dropdown.html.haml
- if current_user.notifications.count > 0
  %li#notifications_menu{class: "backendBarItem dropdown notifications"}
    = link_to notifications_path, class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
      = t(:notifications)
      - if current_user.notifications.unread.count > 0
        %span.badge= current_user.notifications.unread.count
        %b.caret
    - if current_user.notifications.unread.count > 0    
      %ul.dropdown-menu
        %li.read_all= link_to t(:mark_all_notifications_as_read), read_all_notifications_path, remote: true, method: 'patch'
        - current_user.notifications.unread.includes(:author, :reference).order('created_at desc').each do |notification|
          %li= render partial: 'notifications/notification', object: notification

app/views/notifications/_post_notification.html.haml
- # We need the inline styling for emails.

.notification
  %div{style: 'float: left; margin-right: 10px'}
    = user_avatar(notification.author)
  %div{style: 'overflow: hidden'}
    %small
      = link_to notification.author.title, notification.author if notification.author
      = localize(notification.created_at)
    .notification_body
      %p
        %strong= link_to notification.message, notification
      %p= markup notification.text

      %p= render partial: 'posts/attachments', locals: {post: notification.reference}

    .notification_links
      %small
        = link_to t(:write_a_comment), notification

app/views/notifications/_user_status_notification.html.haml
- # We need the inline styling for emails.

.notification
  %div{style: 'float: left; margin-right: 10px'}
    - notification.reference.kind_of?(User) || raise(RuntimeError, 'status notification reference should be a User.')
    = user_avatar(notification.reference)
  %div{style: 'overflow: hidden'}
    %small
      = localize(notification.created_at)
    .notification_body
      %p
        %strong= link_to notification.message, notification
    %small
      = user_avatar(notification.author, size: 16)
      = "Eingetragen von: "
      = link_to notification.author.title, notification.author

app/views/notifications/_welcome_notification.html.haml
- # We need the inline styling for emails.

.notification
  %div{style: 'float: left; margin-right: 10px'}
  %div{style: 'overflow: hidden'}
    %small
      = localize(notification.created_at)
    .notification_body
      %p
        %strong= link_to notification.message, notification
      %p= markup notification.text

app/views/notifications/index.html.haml
%h1.notifications= @title
%div
  - @notifications.each do |notification|
    = render notification